# Generated by Django 5.0.13 on 2025-12-10 21:25

from django.db import migrations
from datetime import date, time, datetime

def seed_data(apps, schema_editor):
    Rol_Produccion = apps.get_model('app_audiovisual', 'Rol_Produccion')
    Miembro_Equipo = apps.get_model('app_audiovisual', 'Miembro_Equipo')
    Proyecto_Audiovisual = apps.get_model('app_audiovisual', 'Proyecto_Audiovisual')
    Escena = apps.get_model('app_audiovisual', 'Escena')
    Material_Grabado = apps.get_model('app_audiovisual', 'Material_Grabado')
    Presupuesto_Detalle = apps.get_model('app_audiovisual', 'Presupuesto_Detalle')
    Contrato_Talento = apps.get_model('app_audiovisual', 'Contrato_Talento')

    # Roles de Producción
    rol_director = Rol_Produccion.objects.create(
        nombre_rol='Director',
        descripcion_rol='Dirige la visión creativa del proyecto.',
        departamento='Dirección',
        salario_promedio=5000.00,
        habilidades_requeridas='Liderazgo, visión creativa, comunicación.'
    )
    rol_productor = Rol_Produccion.objects.create(
        nombre_rol='Productor',
        descripcion_rol='Gestiona los recursos y la logística del proyecto.',
        departamento='Producción',
        salario_promedio=4500.00,
        habilidades_requeridas='Organización, presupuesto, gestión de personal.'
    )
    rol_editor = Rol_Produccion.objects.create(
        nombre_rol='Editor',
        descripcion_rol='Ensambla y edita el material grabado.',
        departamento='Post-producción',
        salario_promedio=3500.00,
        habilidades_requeridas='Manejo de software de edición, narrativa visual.'
    )
    rol_sonidista = Rol_Produccion.objects.create(
        nombre_rol='Sonidista',
        descripcion_rol='Captura y procesa el sonido del proyecto.',
        departamento='Sonido',
        salario_promedio=3200.00,
        habilidades_requeridas='Manejo de equipo de audio, Pro Tools, diseño de sonido.'
    )

    # Miembros del Equipo
    miembro_1 = Miembro_Equipo.objects.create(
        nombre='Juan',
        apellido='Pérez',
        rol=rol_director,
        email='juan.perez@example.com',
        telefono='123456789',
        fecha_contratacion=date(2023, 1, 15),
        salario_base=5500.00,
        especialidad_tecnica='Dirección de Fotografía',
        disponibilidad='Completa'
    )
    miembro_2 = Miembro_Equipo.objects.create(
        nombre='Maria',
        apellido='Gomez',
        rol=rol_productor,
        email='maria.gomez@example.com',
        telefono='987654321',
        fecha_contratacion=date(2023, 2, 1),
        salario_base=5000.00,
        especialidad_tecnica='Producción Ejecutiva',
        disponibilidad='Completa'
    )
    miembro_3 = Miembro_Equipo.objects.create(
        nombre='Carlos',
        apellido='Ruiz',
        rol=rol_editor,
        email='carlos.ruiz@example.com',
        telefono='555555555',
        fecha_contratacion=date(2023, 3, 10),
        salario_base=4000.00,
        especialidad_tecnica='Edición de Sonido',
        disponibilidad='Media Jornada'
    )
    miembro_4 = Miembro_Equipo.objects.create(
        nombre='Lucia',
        apellido='Vargas',
        rol=rol_sonidista,
        email='lucia.vargas@example.com',
        telefono='111222333',
        fecha_contratacion=date(2023, 4, 1),
        salario_base=3300.00,
        especialidad_tecnica='Diseño de Sonido',
        disponibilidad='Completa'
    )

    # Proyectos Audiovisuales
    proyecto_1 = Proyecto_Audiovisual.objects.create(
        titulo='El Amanecer de los Tiempos',
        tipo_produccion='Largometraje',
        fecha_inicio=date(2024, 1, 1),
        fecha_fin_estimada=date(2024, 12, 31),
        presupuesto=1000000.00,
        estado_proyecto='En Producción',
        id_director=miembro_1,
        descripcion='Una película de ciencia ficción sobre viajes en el tiempo.',
        distribucion_prevista='Cines y plataformas de streaming'
    )
    proyecto_2 = Proyecto_Audiovisual.objects.create(
        titulo='Secretos de la Ciudad Perdida',
        tipo_produccion='Documental',
        fecha_inicio=date(2024, 3, 15),
        fecha_fin_estimada=date(2024, 9, 30),
        presupuesto=50000.00,
        estado_proyecto='En Pre-producción',
        id_director=miembro_1,
        descripcion='Un documental que explora una antigua ciudad submarina.',
        distribucion_prevista='Canales de televisión y plataformas de streaming'
    )
    proyecto_3 = Proyecto_Audiovisual.objects.create(
        titulo='Código Rojo',
        tipo_produccion='Serie Web',
        fecha_inicio=date(2024, 5, 20),
        fecha_fin_estimada=date(2024, 11, 30),
        presupuesto=25000.00,
        estado_proyecto='En Guion',
        id_director=miembro_2,
        descripcion='Una serie de misterio sobre un grupo de hackers.',
        distribucion_prevista='YouTube y Vimeo'
    )
    proyecto_4 = Proyecto_Audiovisual.objects.create(
        titulo='Noche Estrellada',
        tipo_produccion='Cortometraje',
        fecha_inicio=date(2024, 8, 1),
        fecha_fin_estimada=date(2024, 8, 31),
        presupuesto=5000.00,
        estado_proyecto='En Pre-producción',
        id_director=miembro_2,
        descripcion='Un cortometraje experimental sobre la soledad en la ciudad.',
        distribucion_prevista='Festivales de cine'
    )

    # Escenas
    escena_1_p1 = Escena.objects.create(
        id_proyecto=proyecto_1,
        numero_escena=1,
        descripcion_escena='El protagonista descubre la máquina del tiempo.',
        localizacion='Laboratorio abandonado',
        fecha_grabacion_estimada=date(2024, 6, 1),
        hora_grabacion=time(9, 0, 0),
        actores_involucrados='Actor A, Actor B',
        equipos_especiales='Máquina de humo, luces estroboscópicas'
    )
    escena_2_p1 = Escena.objects.create(
        id_proyecto=proyecto_1,
        numero_escena=2,
        descripcion_escena='Persecución en las calles de una ciudad futurista.',
        localizacion='Set de croma verde',
        fecha_grabacion_estimada=date(2024, 6, 15),
        hora_grabacion=time(14, 0, 0),
        actores_involucrados='Actor A, Doble de acción',
        equipos_especiales='Cámaras de alta velocidad, drones'
    )
    escena_1_p2 = Escena.objects.create(
        id_proyecto=proyecto_2,
        numero_escena=1,
        descripcion_escena='Entrevista con un arqueólogo marino.',
        localizacion='Oficina del arqueólogo',
        fecha_grabacion_estimada=date(2024, 7, 10),
        hora_grabacion=time(11, 0, 0),
        actores_involucrados='Entrevistador, Arqueólogo',
        equipos_especiales='Micrófonos de solapa, dos cámaras'
    )
    escena_1_p3 = Escena.objects.create(
        id_proyecto=proyecto_3,
        numero_escena=1,
        descripcion_escena='El equipo de hackers se reúne por primera vez.',
        localizacion='Cafetería abandonada',
        fecha_grabacion_estimada=date(2024, 9, 1),
        hora_grabacion=time(18, 0, 0),
        actores_involucrados='Hacker A, Hacker B, Hacker C',
        equipos_especiales='Laptops, equipo de red, pizarra'
    )

    # Material Grabado
    Material_Grabado.objects.create(
        id_escena=escena_1_p1,
        tipo_material='Video',
        duracion_segundos=120,
        formato_archivo='MP4',
        fecha_grabacion_real=datetime(2024, 6, 1, 10, 30, 0),
        ruta_almacenamiento='/mnt/produccion/p1/escena1/toma1.mp4',
        notas_tecnicas='Toma principal, plano medio.',
        version='1.0'
    )
    Material_Grabado.objects.create(
        id_escena=escena_1_p1,
        tipo_material='Audio',
        duracion_segundos=120,
        formato_archivo='WAV',
        fecha_grabacion_real=datetime(2024, 6, 1, 10, 30, 0),
        ruta_almacenamiento='/mnt/produccion/p1/escena1/audio1.wav',
        notas_tecnicas='Audio de la cámara.',
        version='1.0'
    )
    Material_Grabado.objects.create(
        id_escena=escena_2_p1,
        tipo_material='Video',
        duracion_segundos=180,
        formato_archivo='MOV',
        fecha_grabacion_real=datetime(2024, 6, 15, 15, 0, 0),
        ruta_almacenamiento='/mnt/produccion/p1/escena2/toma_dron.mov',
        notas_tecnicas='Toma aérea con dron.',
        version='1.0'
    )
    Material_Grabado.objects.create(
        id_escena=escena_1_p2,
        tipo_material='Video',
        duracion_segundos=600,
        formato_archivo='MP4',
        fecha_grabacion_real=datetime(2024, 7, 10, 11, 30, 0),
        ruta_almacenamiento='/mnt/produccion/p2/escena1/entrevista.mp4',
        notas_tecnicas='Plano cerrado del arqueólogo.',
        version='1.0'
    )

    # Presupuesto Detallado
    Presupuesto_Detalle.objects.create(
        id_proyecto=proyecto_1,
        categoria_gasto='Efectos Visuales',
        descripcion_gasto='Creación de la ciudad futurista en 3D.',
        monto_estimado=250000.00,
        monto_real=0.00,
        fecha_gasto=date(2024, 5, 1),
        aprobado_por='Maria Gomez',
        tipo_moneda='USD'
    )
    Presupuesto_Detalle.objects.create(
        id_proyecto=proyecto_2,
        categoria_gasto='Viajes y Alojamiento',
        descripcion_gasto='Viaje del equipo a la costa para filmar.',
        monto_estimado=5000.00,
        monto_real=0.00,
        fecha_gasto=date(2024, 6, 20),
        aprobado_por='Maria Gomez',
        tipo_moneda='USD'
    )
    Presupuesto_Detalle.objects.create(
        id_proyecto=proyecto_3,
        categoria_gasto='Guionistas',
        descripcion_gasto='Pago a los guionistas por los primeros 3 episodios.',
        monto_estimado=3000.00,
        monto_real=3000.00,
        fecha_gasto=date(2024, 5, 25),
        aprobado_por='Juan Pérez',
        tipo_moneda='USD'
    )
    Presupuesto_Detalle.objects.create(
        id_proyecto=proyecto_1,
        categoria_gasto='Catering',
        descripcion_gasto='Servicio de comida para el equipo durante la filmación.',
        monto_estimado=15000.00,
        monto_real=12000.00,
        fecha_gasto=date(2024, 6, 1),
        aprobado_por='Maria Gomez',
        tipo_moneda='USD'
    )

    # Contratos de Talento
    Contrato_Talento.objects.create(
        id_proyecto=proyecto_1,
        id_miembro=miembro_1,
        fecha_firma=date(2023, 12, 1),
        salario_acordado=60000.00,
        clausulas_especiales='Bono por finalización de proyecto.',
        duracion_contrato='14 meses',
        rol_especifico='Director y Guionista Principal'
    )
    Contrato_Talento.objects.create(
        id_proyecto=proyecto_1,
        id_miembro=miembro_3,
        fecha_firma=date(2024, 4, 15),
        salario_acordado=45000.00,
        clausulas_especiales='Horas extra pagadas al 150%.',
        duracion_contrato='8 meses',
        rol_especifico='Editor de Montaje'
    )
    Contrato_Talento.objects.create(
        id_proyecto=proyecto_2,
        id_miembro=miembro_2,
        fecha_firma=date(2024, 2, 20),
        salario_acordado=55000.00,
        clausulas_especiales='Participación en los beneficios netos del 5%.',
        duracion_contrato='7 meses',
        rol_especifico='Productora Ejecutiva y Directora de Investigación'
    )
    Contrato_Talento.objects.create(
        id_proyecto=proyecto_3,
        id_miembro=miembro_4,
        fecha_firma=date(2024, 5, 10),
        salario_acordado=38000.00,
        clausulas_especiales='Ninguna',
        duracion_contrato='6 meses',
        rol_especifico='Sonidista principal de la serie web'
    )

def reverse_seed_data(apps, schema_editor):
    Rol_Produccion = apps.get_model('app_audiovisual', 'Rol_Produccion')
    Miembro_Equipo = apps.get_model('app_audiovisual', 'Miembro_Equipo')
    Proyecto_Audiovisual = apps.get_model('app_audiovisual', 'Proyecto_Audiovisual')
    Escena = apps.get_model('app_audiovisual', 'Escena')
    Material_Grabado = apps.get_model('app_audiovisual', 'Material_Grabado')
    Presupuesto_Detalle = apps.get_model('app_audiovisual', 'Presupuesto_Detalle')
    Contrato_Talento = apps.get_model('app_audiovisual', 'Contrato_Talento')

    # Eliminar en orden inverso a la creación para evitar problemas de Foreign Keys
    Contrato_Talento.objects.all().delete()
    Presupuesto_Detalle.objects.all().delete()
    Material_Grabado.objects.all().delete()
    Escena.objects.all().delete()
    Proyecto_Audiovisual.objects.all().delete()
    Miembro_Equipo.objects.all().delete()
    Rol_Produccion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app_audiovisual', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
