# Generated by Django 5.0.13 on 2025-12-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escena',
            fields=[
                ('id_escena', models.AutoField(primary_key=True, serialize=False)),
                ('numero_escena', models.IntegerField()),
                ('descripcion_escena', models.TextField()),
                ('localizacion', models.CharField(max_length=255)),
                ('fecha_grabacion_estimada', models.DateField()),
                ('hora_grabacion', models.TimeField()),
                ('actores_involucrados', models.TextField()),
                ('equipos_especiales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Equipo',
            fields=[
                ('id_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidad_tecnica', models.CharField(max_length=100)),
                ('disponibilidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Produccion',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion_rol', models.TextField()),
                ('departamento', models.CharField(max_length=50)),
                ('salario_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habilidades_requeridas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_Grabado',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(max_length=50)),
                ('duracion_segundos', models.IntegerField()),
                ('formato_archivo', models.CharField(max_length=20)),
                ('fecha_grabacion_real', models.DateTimeField()),
                ('ruta_almacenamiento', models.CharField(max_length=255)),
                ('notas_tecnicas', models.TextField()),
                ('version', models.CharField(max_length=10)),
                ('id_escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.escena')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Audiovisual',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_produccion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_proyecto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('distribucion_prevista', models.CharField(max_length=100)),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.miembro_equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto_Detalle',
            fields=[
                ('id_item_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_gasto', models.CharField(max_length=100)),
                ('descripcion_gasto', models.TextField()),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('aprobado_por', models.CharField(max_length=100)),
                ('tipo_moneda', models.CharField(max_length=10)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.proyecto_audiovisual')),
            ],
        ),
        migrations.AddField(
            model_name='escena',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.proyecto_audiovisual'),
        ),
        migrations.CreateModel(
            name='Contrato_Talento',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_firma', models.DateField()),
                ('salario_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clausulas_especiales', models.TextField()),
                ('duracion_contrato', models.CharField(max_length=50)),
                ('rol_especifico', models.CharField(max_length=100)),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.miembro_equipo')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.proyecto_audiovisual')),
            ],
        ),
        migrations.AddField(
            model_name='miembro_equipo',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_audiovisual.rol_produccion'),
        ),
    ]
